### PR TITLE
Delete migrate_wiki.py

### PR DESCRIPTION
**Pull request by abitrolly**
Not actual anymore. @pypingou

### CODE REVIEW

**Comment by Zlopez** [comment]
This pull request **fixes 1 alert** when merging 8ebbbe9809961e98f5558f09075cfa4b2e1b9dd5 into 44e7fb7ecd7bcc4284d100939080c20d6b00dfe1 - [view on LGTM.com](https://lgtm.com/projects/g/release-monitoring/anitya/rev/pr-8e8e8d3b14846f517c0e8cefb178b376841231ca)

**fixed alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by pypingou** [comment]
Snif, a part of history is going :)

**Comment by Zlopez** [comment]
This pull request **fixes 1 alert** when merging d8bbd0e6be5234836cb29a073d3927e2727d268a into cce9da8af0fe33db72d1a56691bfb4368a4f56d0 - [view on LGTM.com](https://lgtm.com/projects/g/release-monitoring/anitya/rev/pr-01602c6fdfb966beeca017185121a953fd810cfa)

**fixed alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Zlopez** [comment]
This pull request **fixes 1 alert** when merging dd90246f0c9c46e390d551af54a2e17bd159b23f into 1533a000508eb1960113b353c69a917ec99ce477 - [view on LGTM.com](https://lgtm.com/projects/g/release-monitoring/anitya/rev/pr-5119e1bb68b53e5f254e00c0321491325b52c1ce)

**fixed alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by abitrolly** [comment]
> Snif, a part of history is going :)
>
`git history` will take care of that for software archaeologists. :)

**Pull request merged**
