### PR TITLE
Actually store latest known version cursor

### PR DESCRIPTION
**Pull request by nphilipp**
This is a little embarassing but #863 doesn't really store the latest known cursor because of a bug in `check_project_release()`. Additionally to fixing this, improve the GitHub tests and migration script and be a little more strict about accepted API responses.

### CODE REVIEW

**Comment by nphilipp** [comment]
Hang on, aside from the news file I need to figure out what the issue with coverage is here.

**Comment by Zlopez** [comment]
Could you squash the commits, when you think this is ready for merge?

**Comment by nphilipp** [comment]
> Could you squash the commits, when you think this is ready for merge?

Of course.

**Comment by nphilipp** [comment]
And this is it with the commits squashed, except the one fixing an unrelated typo.

**Comment by nphilipp** [comment]
That's what I get for committing without running flake8 myself, sorry. :wink:

**Comment by Zlopez** [comment]
Yeah, it's good to have it in tests

**Pull request merged**
