### PR TITLE
Add database schema image to repository

### LINKED ISSUE #692: Store database schema picture in repository
It is handy to have the picture https://release-monitoring.org/static/docs/database.html#database-schema versioned in `docs/` for historical purpose.

image

### PR DESCRIPTION
**Pull request by Zlopez**
Database image was missing in the documentation, because it was not in
the repository. This commit is fixing this.

Fixes #692

Signed-off-by: Michal Konečný <mkonecny@redhat.com>

### CODE REVIEW

**Comment by abitrolly** [comment]
With no command to regenerate the image, it is likely that the image get outdated. The best way to ensure that DB schema is up to date is to regenerate the schema and compare the result in CI.

**Comment by Zlopez** [comment]
The image is generated as part of the documentation building (which is done every time tox is executed). I will add this step as part of the release process which should be enough to keep the image up to date.

**Comment by abitrolly** [comment]
The image is present on `release-monitoring` doc domain

https://release-monitoring.org/static/docs/database.html#database-schema

but not on `readthedocs.io`

https://anitya.readthedocs.io/en/stable/database.html#database-schema

**Comment by Zlopez** [comment]
It will be after this PR is merged.

**Comment by Zlopez** [comment]
I updated the release process documentation with new step for generating a new DB schema image.

**Comment by abitrolly** [comment]
@Zlopez release process is not automated at all?

**Comment by Zlopez** [comment]
Only part of it is automated (deployment in OpenShift), but otherwise it still contains manual steps to do.

**Comment by abitrolly** [comment]
Can be automated later.

**Comment by Zlopez** [comment]
I created an issue for this #880

**Pull request merged**
