### PR TITLE
Mock the Fedora Messaging calls in the unit tests

### PR DESCRIPTION
**Pull request by abompard**
This should make the tests much faster since they won't wait for the publish timeout anymore.

### CODE REVIEW

**Comment by Zlopez** [comment]
Could you fix the formatting issue? And could you add news file for this change `PR860.dev`?

**Comment by nphilipp** [comment]
> Could you fix the formatting issue? And could you add news file for this change `PR860.dev`?

On it, this unblocks a couple other PRs whose CI tests fail.

**Comment by Zlopez** [comment]
It looks like some of the mocks are still missing.

**Comment by nphilipp** [comment]
I've come across a couple of places where messaging calls still need to be mocked out. Stay tuned.

**Comment by Zlopez** [comment]
@Mergifyio refresh

**Pull request merged**
