### PR TITLE
Add basic release process guide

### PR DESCRIPTION
**Pull request by jeremycline**
These are the steps I follow when making a release.

### CODE REVIEW

**Comment by Zlopez** [comment]
There is already basic release process described in https://pagure.io/infra-docs/blob/master/f/docs/sysadmin-guide/sops/anitya.rst
Could you update this also there?

**Comment by jeremycline** [comment]
So that stuff is for deploying new upstream releases, and this is for making new releases in upstream. Do you want those docs pointing at these docs, or something else?

**Comment by Zlopez** [comment]
I just want if you could review the https://pagure.io/infra-docs/blob/master/f/docs/sysadmin-guide/sops/anitya.rst and say if this is correct.
I did some changes to the SOP.

**Comment by Zlopez** [comment]
Thanks

**Pull request merged**
