### PR TITLE
Add `docker build` testing to Travis

### PR DESCRIPTION
**Pull request by abitrolly**
As a followup to #798 I decided to test if Docker build is still operational, continuously.

### CODE REVIEW

**Comment by Zlopez** [comment]
Dockerfile is really outdated, so I'm not sure if the Anitya in docker will run at all.

**Comment by abitrolly** [comment]
@pypingou it is not ready yet. I am going to make proper stages, so the test will fail faster on improper linting etc.

**Comment by abitrolly** [comment]
@pypingou ready to be merged.

**Comment by Zlopez** [comment]
@abitrolly Could you squash the commits and add news file?
See https://anitya.readthedocs.io/en/stable/contributing.html#release-notes

**Comment by abitrolly** [comment]
@Zlopez done.

**Comment by abitrolly** [comment]
Not sure what `codecov` is waiting for. Build seems to be processed successfully https://codecov.io/gh/release-monitoring/anitya/commit/48b446a2261608c5aee6c10bcc316c00abae2be4

Reported upstream https://community.codecov.io/t/codecov-status-stuck-at-waiting-for-status-to-be-reported/406

**Pull request merged**
